name: mc-JoinleavePlungin
version: '${project.version}'
main: com.mc.newprompter.mcjoinleaveplungin.Mc_JoinleavePlungin
api-version: 1.20
description: A simple plugin to beautify join and leave messages.
authors: [mengnankk]  
